### ISSUE TITLE
if apply domain MLM-finetuning for rescoring

### ISSUE THREAD

**Issue by yyht** [awslabs/mlm-scoring#10]
hi, I am little confused on rescoring for asr and nmt.
Is it post-pretrained on domain corpus for rescoring(apply MLM on domain data) or just used open-source pretrained model(roberta or bert on wikibook corpus)?

**Comment by JulianSlzr** [comment]
Hi @yyht, sorry for the late response. The examples here use the public models as-is. For the paper's ASR experiments we also include results after continued pre-training of BERT on the LibriSpeech corpus before scoring and maskless finetuning. We have not released that LibriSpeech-BERT model but I hope to develop better speech-adapted LMs for the future. You can also swap in your own BERT if desired.
