### ISSUE TITLE
Increasing batch size when using command-line mlm score

### ISSUE THREAD

**Issue by ajd12342** [awslabs/mlm-scoring#4]
I am trying to use this package's command-line interface in a similar fashion to the README's example:
```
mlm score \
    --mode hyp \
    --model bert-base-en-uncased \
    --gpus 0 \
    examples/asr-librispeech-espnet/data/dev-other.am.json \
    > examples/demo/dev-other-3.lm.json
```
However, I see that it uses only around 601 MB of GPU memory, which is much less that what the GPU is able to support (12 GB). Is there any way to increase the batch size when using `mlm score`? It seems that the `--split-size` argument would do something like this, is that right?

**Comment by JulianSlzr** [comment]
That's right. You can see an example in the README.md in the BLIMP example (https://github.com/awslabs/mlm-scoring/tree/master/examples/lingacc-blimp) where I use a 500 split-size for the large models but 1500 for the base model.
