### ISSUE TITLE
How to integrate this with MuRIL?

### ISSUE THREAD

**Issue by BarahFazili** [awslabs/mlm-scoring#7]
I wanted to use this library for computing the scores for MuRIL which is based on BERT MLM.Its not there in huggingface as yet.How to bridge the gap?

**Comment by davisliang** [comment]
There are two ways to go about this:

1. Perhaps check out the model zoo in huggingface. From a cursory search, there seems to be a model uploaded for MuRIL cased: https://huggingface.co/simran-kh/muril-cased-temp/tree/main
2. You can convert Tensorflow parameters to Torch and directly load them into your instantiated BERT encoder: https://huggingface.co/transformers/v1.0.0/converting_tensorflow_models.html

**Comment by BarahFazili** [comment]
Yes,, I was able to merge the MuRIL model here using [https://huggingface.co/monsoon-nlp/muril-adapted-local].Thanks!

**Comment by BarahFazili** [comment]
Yes,I was able to merge the MuRIL model here using [](https://huggingface.co/monsoon-nlp/muril-adapted-local)Thanks !

**Comment by BarahFazili** [comment]
Yes,, I was able to merge the MuRIL model here using [https://huggingface.co/monsoon-nlp/muril-adapted-local)](https://huggingface.co/monsoon-nlp/muril-adapted-local)Thanks !
